---
- hosts: tomcat
  become: yes
  become_method: sudo

  tasks: 
   - name: Install Java 
     apt: name=default-jdk state=present

   - name: Install Tomcat
     apt: name=tomcat8 state=present


   - name: Install Tomcat admin
     apt: name=tomcat8-admin state=present
  
   - name: Configure Tomcat users
     copy:
       src: server.xml
       dest: /etc/tomcat8/
       owner: root
       group: tomcat8
       mode: 0640

   - name: Stop the firewall
     service:
       name: ufw
       state: stopped

   - name: wait for tomcat to start
     wait_for: port=8080


#/var/lib/tomcat8/webapps
