---
- hosts: tomcat
  serial: 1
  become: yes
  become_method: sudo
  vars:
    package_name: package_name.war

  tasks:
   - name: Install Java
     apt: name=default-jdk state=present

   - name: Install Tomcat
     apt: name=tomcat9 state=present

   - name: Install Tomcat admin
     apt: name=tomcat9-admin state=present

   - name: Configure Tomcat users
     copy:
       src: tomcat-users.xml
       dest: /etc/tomcat9/
       owner: root
       group: tomcat9
       mode: 0640

   - name: Stop the firewall
     service:
       name: ufw
       state: stopped

#   - name: restart tomcat
#     service:
#       name: tomcat9
#       state: restarted


#   - name: wait for tomcat to start
#     wait_for: port=8080

   - name: deploy the generated package to tomcat
     copy:
       src: package_name.war
       dest: /var/lib/tomcat8/webapps/
       mode: 0640
