---
- hosts: web
  serial: 1
  become: yes
  become_method: sudo

  tasks:
  - name: Add the user 'james' with a bash shell, appending the group 'root' to the user's groups
    ansible.builtin.user:
      name: james
      shell: /bin/bash
      groups: root
      append: yes

 #  - name: Remove the user 'johnd'
 #    ansible.builtin.user:
 #     name: johnd
 #     state: absent
 #     remove: yes

# refrences : https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
