---
- name: create user devops on node
  hosts: web
  become: yes
  become_method: sudo
  vars:
    pkgs:
      - nginx
      - postfix
  tasks:
  - name: Is Bind Installed?
    apt: name={{ pkgs }} state=absent
    register: servicecheck
  - debug:
      var: servicecheck


  - name: Install a list of packages
    apt:
      pkg:
      - vim 
      - tomcat9
      state: absent
      autoremove: true
      autoclean: true


    register: servicecheck2
  - debug:
      var: servicecheck2
  
